spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:7000"
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8000/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:7000"